import type { Metadata } from "next";
import Link from "next/link";

import "@/css/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <div className={"wrapper"}>
          <div>
            <header className={"header"}>
              <h1 className={"logo"}>Surface Detail</h1>
              <p>
                Harkening back to the early internet in order to imagine the
                future
              </p>
              <nav className={"nav"}>
                <ul>
                  <li>
                    <Link href="/">Home</Link>
                  </li>
                  {/* <li>
                    <Link href="/posts">Posts</Link>
                  </li> */}
                  <li>
                    <a target="_blank" href="https://github.com/liamegan">
                      GitHub
                    </a>
                  </li>
                </ul>
              </nav>
            </header>
          </div>
          <div className={"main"}>{children}</div>
        </div>
      </body>
    </html>
  );
}
